modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/abnormals-core/issues"
license = "https://github.com/team-abnormals/abnormals-core/blob/main/LICENSE.txt"

[[mods]]
    modId = "abnormals_core"
    version = "3.0.0"
    logoFile = "abnormals_core.png"
    authors = "Team Abnormals"
    credits = "SmellyModder (Luke Tonon), bageldotjpg, and Jackson"
    displayName = "Abnormals Core"
    description = '''
    Library mod for all Abnormals mods.
    '''

[[dependencies.abnormals_core]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.abnormals_core]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"